"""add track_id to students table

Revision ID: f6413fae65ce
Revises: e5e8960ebb03
Create Date: 2024-09-02 11:09:20.083557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6413fae65ce'
down_revision = 'e5e8960ebb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tracks', ['track_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('track_id')

    # ### end Alembic commands ###
